### ISSUE TITLE
Parameter for cnvkit in Readme need change

### ISSUE THREAD

**Issue by ZanderZhai** [jluebeck/PrepareAA#14]
Hello,

I notice that you have integrate cnvkit into docker and we can start PAA with only sorted bam. It will use cnvkit in docker for seed generation with option `--run_cnvkit`.  It has changed in software but not change in [Readme](https://github.com/jluebeck/PrepareAA#starting-from-sorted-bam-using-cnvkit-for-seed-generation).
I think it should change to this, right?
```
/path/to/PrepareAA/PrepareAA.py -s sample_name  -t number_of_threads --run_cnvkit  --sorted_bam sample.cs.rmdup.bam [--run_AA]
``` 
Thanks for you work to make this pipeline !

**Comment by jluebeck** [comment]
Hi, 

Great suggestion - I updated the docker section of the readme to provide an example command for using the docker script with --run_cnvkit. The main script still requires the user to specify the the location of CNVKit. 

Please let me know if there are other things I can make more clear.

Best regards,
Jens
