### ISSUE TITLE
Always stuck at "Plotting SV View"

### ISSUE THREAD

**Issue by notchw** [jluebeck/PrepareAA#17]
Dear author:

I am running AA many times (by PrepareAA), but the execution always stuck at "Plotting SV View"
Besides, the summary.txt shown that " #Amplicons = 8 "
But my results always cannot save image when the " Intervals more then one chromosome"
(No matter how many times I redo it)
![image](https://user-images.githubusercontent.com/84956744/127595075-c1a3983f-2d29-4d19-9c39-39d6659713cc.png)
Can you help me to solve this problem? Thanks!

**Comment by jluebeck** [comment]
Hi, could you please share the AA or PAA command you ran? One of the biggest issues with stalling in AA is improperly selected seed regions. Would you also be able to share info on how you selected inputs for AA, and how many entries are in the bed file you pass to AA?

Thanks,
Jens

**Comment by notchw** [comment]
Dear Jens:

Thanks for your reply.
I am directly running the command of PAA. (My WGS data is 5X)
The command as shown below:

time /pkg/PrepareAA/PrepareAA.py -s eMMHGS-001-N -t 32 --cnvkit_dir
/usr/local/bin/cnvkit.py --sorted_bam
/project/GP1/jeff1wasai/nhri/eMMHGS/eMMHGS-001/eMMHGS-001-N/eMMHGS-001-N_sorted_markdup.bam
--ref GRCh38 --run_AA  > eMMHGS-001-AA-2.log.txt 2>&1


I have less experience with AA. All of the commands that I used are default
values.

I am very sorry that I don't know how many entries are in the file I pass
to AA.


If you don't mind, could you please refer to the attached file of my log
for more details.

Thank you very much.



Sincerely,

HW

Hui Wen ***@***.***> 於 2021年8月2日 週一 上午9:45寫道：

**Comment by notchw** [comment]
Dear Jens:

Thanks for your reply.
I am directly running the command of PAA. (My WGS data is 5X)
The command as shown below:

time /pkg/PrepareAA/PrepareAA.py -s eMMHGS-001-N -t 32 --cnvkit_dir /usr/local/bin/cnvkit.py --sorted_bam /project/GP1/jeff1wasai/nhri/eMMHGS/eMMHGS-001/eMMHGS-001-N/eMMHGS-001-N_sorted_markdup.bam --ref GRCh38 --run_AA  > eMMHGS-001-AA-2.log.txt 2>&1

I have less experience with AA. All of the commands that I used are default values. 
I am very sorry that I don't know how many entries are in the file I pass to AA.
If you don't mind, could you please refer to my log for more details by e-mail .

Thank you very much.

**Comment by jluebeck** [comment]
Hi, 

Thank you much for providing this info, I think any log files would be helpful, you can send them to me at jluebeck` [ a t] `ucsd.edu. 

I'll also add that the warnings you are seeing are harmless and part of the expected output. 

The error "Numpy LinAlgError when forming amplicon plot" is a bug in Matplotlib, and causes no amplicon image to be saved, however the text files _graph.txt and _cycles.txt used for downstream amplicon classification will be present, and the error is not fatal for AA.

I will also mention that when it hangs on "Plotting SV View", there are other steps happening concurrently to resolve the amplicon decomposition, and this process can sometimes take extreme amounts of time for complex samples. When you say that it hangs, how long are you waiting?

We have not had any issues with amplicons containing multiple chromosomes consistently failing visualization in AA, and I think the issue is rather that there is a complex structure AA is stuck on. 

Thanks,
Jens

**Comment by notchw** [comment]
Dear Jens:

Thanks for your reply.
More than 5-7 days, when the AA hangs on "Plotting SV View."

I send my logs to your email.
Please check it.
Thank you very much.

**Comment by Bio-LiHe** [comment]
> 



> Hi,
> 
> Thank you much for providing this info, I think any log files would be helpful, you can send them to me at jluebeck`[ a t]`ucsd.edu.
> 
> I'll also add that the warnings you are seeing are harmless and part of the expected output.
> 
> The error "Numpy LinAlgError when forming amplicon plot" is a bug in Matplotlib, and causes no amplicon image to be saved, however the text files _graph.txt and _cycles.txt used for downstream amplicon classification will be present, and the error is not fatal for AA.
> 
> I will also mention that when it hangs on "Plotting SV View", there are other steps happening concurrently to resolve the amplicon decomposition, and this process can sometimes take extreme amounts of time for complex samples. When you say that it hangs, how long are you waiting?
> 
> We have not had any issues with amplicons containing multiple chromosomes consistently failing visualization in AA, and I think the issue is rather that there is a complex structure AA is stuck on.
> 
> Thanks, Jens

Hi,

I have encountered the same problem. AA hangs on "Plotting SV View." 

Excuse me, how to solve this?

**Comment by jluebeck** [comment]
On rare occasions, samples with large numbers of breakpoints can take up to a week to finish running (possibly more). You can also send me the command you ran and the logfile from AA so I can ensure there are not any obvious issues. For AA, 14 hours is unsurprising if it is an extremely complex set of rearrangements.

Thanks,
Jens
