### ISSUE TITLE
less number break points

### ISSUE THREAD

**Issue by sarmadmehmood89** [jluebeck/PrepareAA#23]
Hi,

I am using Amplicon Arhitect with Pre AA for COLO320DM sample, 

[https://www.ncbi.nlm.nih.gov/sra/SRX11096731[accn](https://www.ncbi.nlm.nih.gov/sra/SRX11096731%5baccn)]

1. I am mapping the fastq files by using PreAA and then I am using CNV kit on the bam files for seed generation, i could see that i have lesser coverage in amplicons, i am curious whether this is the reason that I am getting lesser break points. The coverage seems to be similar when comparing the MYC amplicon in COLO320 and literature but is lesser for other amplicons. Does it have to anything with memory for mapping or something else, can you please suggest something.

2. Can i use amplicon_architect for searching for ecDNA present on sex chromosomes in humans?

Many thanks

Sarmad

**Comment by jluebeck** [comment]
Hi Sarmad,

I would have to see the AA outputs to know if it is significantly different coverage for the other amplicons and what exactly you are comparing to. You can email me at jluebeck [ at ) ucsd.edu if you want to send your results (both yours and what you are comparing with).

AA can be used on non-autosomes. Keep in mind that there are significant number of regions on those chromosomes that are highly repetitive and are thus ignored by AA. You can see those regions in the AA data repo (excludable regions file).

Jens

**Comment by sarmadmehmood89** [comment]
Hi Jens

Many thanks for your feedback. I look forward using Amplicon_architect in my projects.

Sarmad
