### ISSUE TITLE
amplified_intervals.py: error: unrecognized arguments: --ref GRCh38

### ISSUE THREAD

**Issue by zhang919** [jluebeck/PrepareAA#7]
Dear,
I am interesting to apply PrepareAA on my work, and I am happy to hear that it supports hg38-aligned data. but when I run it with --ref GRCh38 --run_AA parameter , I got this error. Could you please help me solve it？Thanks for your attention.

> Wrote /mnt/h/circle-map/2020411/cnvkit_output/sorted_unknown_circle.cns with 1414 regions
> Running amplified_intervals
> python /home/zhangjiayu/bioinfo/AmpliconArchitect/src/amplified_intervals.py --ref GRCh38 --bed /mnt/h/circle-map/20204
> 11/cnvkit_output/sorted_unknown_circle_CNV_GAIN.bed --bam sorted_unknown_circle.bam --gain 4.0 --cnsize_min 10000 --out
>         /mnt/h/circle-map/2020411/ERR181167.1_AA_CNV_SEEDS
> usage: amplified_intervals.py [-h] --bed FILE [--out FILE] [--bam FILE]
>                               [--gain GAIN] [--cnsize_min CNSIZE_MIN]
> amplified_intervals.py: error: unrecognized arguments: --ref GRCh38
> Running AA with default arguments (& downsample 10). To change settings run AA separately.
> python /home/zhangjiayu/bioinfo/AmpliconArchitect/src/AmpliconArchitect.py --ref GRCh38 --downsample 10 --bed /mnt/h/ci
> rcle-map/2020411/ERR181167.1_AA_CNV_SEEDS.bed --bam sorted_unknown_circle.bam --out /mnt/h/circle-map/2020411//ERR18116
> 7.1_AA_results/ERR181167.1

Best.
Zhang.

**Comment by jluebeck** [comment]
Hi Zhang - thanks for providing the error log. Could you confirm you are using the AA code from my fork?
https://github.com/jluebeck/AmpliconArchitect

Best,
Jens

**Comment by zhang919** [comment]
Hi jluebeck, Thanks for timely response，I am sorry to say I miss this point （my AA code is clone from https://github.com/virajbdeshpande/AmpliconArchitect） . I reclone the code from correct fork, and it work well. 
Can you allow me to ask one more stupid question？ Do you think run AA code from virajbdeshpande repo after patch your data_repo with --ref GRCh38 and my own called CNV intervals is the reason for this issue: https://github.com/virajbdeshpande/AmpliconArchitect/issues/66
Thanks for your work again.
Best.
Zhang.

**Comment by jluebeck** [comment]
Hi Zhang,

No problem - I recently changed the documentation to make it more clear that my fork is required. 

Excellent catch - the cycle visualization tool is not compatible with hg38 and that is likely the cause of the issue you have. I will comment on the issue you mentioned to help Viraj (and myself) debug it in the future. 

Alternatively, there is a non-interactive way to visualize cycles I have created, called (CycleViz)[https://github.com/jluebeck/CycleViz]. Perhaps it would be helpful for you? There is a script there you would need to run on the cycles file to get it into the format CycleViz uses.

Best,
Jens

**Comment by zhang919** [comment]
Hi jluebeck, Thank you for responding so passionately to my questions，I am try deploy CycleViz in my computer. Your prefect works make AA easy to use. Forgive me for asking some more questions in the future. 
If you don't mind, I would open this ticket until I don't have any question about it.
Best.
Zhang.

**Comment by zhang919** [comment]
Dear @jluebeck,
Sorry for more question. Recently I am applying PrepareAA on my data. But I have encountered some confusing problems; if you can give me some suggestions, I will be very grateful.
Firstly,I executed the PrepareAA with the following command：
`python ~/bioinfo/PrepareAA/PrepareAA.py -s name  -t 32 --cnvkit_dir ~/bioinfo/cnvkit/cnvkit.py --sorted_bam bam_file --ref GRCh38 --python3_path /usr/bin/python3_dir --cngain 4 --cnsize_min 10000 --run_AA`
but, I meet a error like this when the program running into finally step.

> File "/home/user/bioinfo/AmpliconArchitect/src/hg19util.py", line 269, in intersects
>     if (int(a[1])-int(b[1]))*(int(a[2])-int(b[1])) <= 0:
> ValueError: cannot convert float NaN to integer
> Completed
I have tow questions about it.
1) I do n’t know what caused this error and caused the program to terminate. Is there any way to eliminate this fault?
2) More importantly, I noticed that the error message contains a confusing path ( /home/user/bioinfo/AmpliconArchitect/src/hg19util.py ) even though I have specified the reference genome as hg38 (or GRCh38). then I want to read the code in hg19util.py file. I noticed the following paragraph:

> ##This is a suite to load hg19 genome, genes, exons, repeat content and perform operations on this genome, compare variants

So, it is looks like the "hg19util.py" is designed for  hg19 genome, is it like this？

In addition, I also meet some warnings may raise by cnvkit like this:

> /home/user/bioinfo/cnvkit/cnvlib/smoothing.py:197: RuntimeWarning: invalid value encountered in greater
>   bad_idx = (y > x.max()) | (y < x.min())

Should I ignore this warning? 

Thanks for your reading very much. I am sorry for ask so many stupid question, and thanks for your kindly help again.

**Comment by jluebeck** [comment]
Hi, 

1. Regarding the ValueError, could you please let me know which version of pysam you are using?

2.  'hg19util.py' is a very bad/misleading filename. The file does not specifically deal with hg19, and this library can handle anything related to hg38 or GRCh37. I have considered changing the filename, but it will probably create bugs as I continue to support hg38 with new changes made by Viraj.

3. Regarding CNVkit, you may want to ask the CNVkit developer specifically - but in my experience, as long as the output files are reasonable such errors are usually not problematic.

**Comment by zhang919** [comment]
Hi @jluebeck ,
1. I run AA in a conda environment， This is a list of all related packages:
`conda list`
# packages in environment at /home/usr/miniconda3/envs/Amplicon:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports_abc             0.5                        py_1    conda-forge
binutils_impl_linux-64    2.34                 h53a641e_0    conda-forge
binutils_linux-64         2.34                hc952b39_18    conda-forge
bioconductor-dnacopy      1.60.0            r36h6e990d7_0    bioconda
biopython                 1.76             py27h516909a_0    conda-forge
bwidget                   1.9.14                        0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2016.9.26                py27_0    conda-forge
cnvkit                    0.9.7b1                   dev_0    <develop>
curl                      7.69.1               h33f0ec9_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
enum34                    1.1.10           py27h8c360ce_1    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.1               he06d7ca_0    conda-forge
fribidi                   1.0.9                h516909a_0    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
future                    0.18.2           py27h8c360ce_1    conda-forge
futures                   3.3.0            py27h8c360ce_1    conda-forge
gcc_impl_linux-64         7.3.0                hd420e75_5    conda-forge
gcc_linux-64              7.3.0               h553295d_18    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gfortran_impl_linux-64    7.3.0                hdf63c60_5    conda-forge
gfortran_linux-64         7.3.0               h553295d_18    conda-forge
glib                      2.64.2               h6f030ca_0    conda-forge
graphite2                 1.3.13            he1b5a44_1001    conda-forge
gsl                       2.6                  h294904e_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_5    conda-forge
gxx_linux-64              7.3.0               h553295d_18    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
htslib                    1.9                  h4da6232_3    bioconda
icu                       64.2                 he1b5a44_1    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py27he6710b0_0  
krb5                      1.17.1               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.69.1               hf7181ac_0    conda-forge
libdeflate                1.5                  h516909a_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.9.2                he1b5a44_0    conda-forge
make                      4.3                  h516909a_0    conda-forge
matplotlib                2.2.5                         1    conda-forge
matplotlib-base           2.2.5            py27h250f245_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.1                      py27_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.16.6                   pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
pandas                    0.24.2           py27hb3f55d8_0    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    6.2.1            py27hd70f55b_1    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pomegranate               0.12.2           py27h9e3301b_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyfaidx                   0.5.8                      py_1    bioconda
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py27hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pysam                     0.15.4           py27hbcae180_0    bioconda
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py27hdf8410d_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
r-base                    3.6.3                h316533a_2    conda-forge
r-cghflasso               0.2_1           r36h6e990d7_1003    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
reportlab                 3.5.42           py27heca39a3_0    conda-forge
samtools                  1.9                 h10a08f8_12    bioconda
scikit-learn              0.20.4                   pypi_0    pypi
scipy                     1.2.1            py27h921218d_2    conda-forge
sed                       4.7               h1bed415_1000    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
singledispatch            3.4.0.3               py27_1000    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
subprocess32              3.5.4            py27h516909a_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tktable                   2.10                 h555a92e_3    conda-forge
tornado                   5.1.1           py27h14c3975_1000    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
yaml                      0.2.4                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h6597ccf_3    conda-forge

Thank you for your help and suggestions again.

**Comment by zhang919** [comment]
Hi @jluebeck,
I recently noticed in the process of AA that it will takes a long time when input some large DNA Interval as seeds, but on the other hand, AA does not seem to occupy all the computing resources so that there are still Idle CPU and memory, so can it be speeded up by multithreads (or other means)? 
Best.
Zhang.

**Comment by jluebeck** [comment]
Unfortunately AA itself runs in serial - and this is more or less necessary as much of the work cannot be parallelized. Sometimes AA takes a very long time to run unfortunately. How large is your seed interval? Did you run `amplified_intervals.py` prior to running AA? If using PAA the `amplified_intervals.py` script will be run by default.

**Comment by zhang919** [comment]
Thanks for your attention, Yes I am using PAA, with the default cnsize_min and cnsize_min, I got 800+ intervals (Many of them are larger than 100kb), the seed file look like this:

`chr1	3721107	3901074	10.8794973634	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	6515586	6685554	10.5559169491	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	7730359	7855336	38.8219316924	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	10094917	10479846	19.4617562332	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	10944759	11259700	28.5880513755	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	11644628	12389489	14.2576042059	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	15054264	15559492	5.89278651131	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	18839206	19259215	35.7149511157	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	20629245	21004253	13.4871161933	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	22889294	24184323	6.21748016515	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	27724400	29329435	6.76064081278	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	34784554	36479591	7.44308132866	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	37474613	38024625	10.6325077395	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	38834643	38929645	20.8516551432	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	39279652	41164694	10.9870762276	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	42149715	47379829	5.99691282081	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	51739925	51844927	80.9663198892	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	52329937	53289958	14.6560801133	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	53764969	54244979	9.75322946805	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	54579987	55180000	24.9176215422	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	56640032	57075041	6.99250800357	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
chr1	59810101	60075107	9.68975373483	/mnt/disk/data/5.8/cnvkit_output/SRR11119296_sorted_unknown_circle_CNV_GAIN.bed
.........
`
Unfortunately, One problem that confuses me is that I have been running PAA on a GCP server with 32 CPUs and 32g of memory for about 3 days, but currently it seems that it still only completes a small part （less than 100 intervals). 

I also noticed a lot of warnings like the following, I don't know if this will affect the speed of the program：

> [root:INFO]	#TIME 3.432	Exploring interval: chr1	3721107	3901074
> [root:WARNING]	dnlists do not match 129 128
> [root:WARNING]	dnlist0: chr11:130183056+->chr11:118502014+ 2
> ......

Could you please give me more advises about the speed?

**Comment by jluebeck** [comment]
Hi,

How did you generate the CN calls? Either this sample has an extraordinary amount of amplification or there is some sort of issue with the CN calls, and you may want to rule out the later somehow.

Completing 100 intervals in 3 days sounds about right for the speed of AA. I have rarely seen a sample have more than 20 total intervals - thus I am wondering why there are 800+ intervals. On the 100 that have finished, what did AA say the CN of those intervals was compared to the CN specified in the CNV bed? You can see AA's prediction of the CN in the graph or cycles files.

 In this case,you could try running PrepareAA with 
`--cnsize_min 200000 --cngain 10` 

The warning that you posted is harmless and telling you that some read(s) got filtered during the breakpoint detection process.

**Comment by zhang919** [comment]
Hi
Thank you for your helpful suggestions, I use PAA to complete the CNV call using the following parameters：
`python ~/bioinfo/PrepareAA/PrepareAA.py -s name -t 32 --cnvkit_dir ~/bioinfo/cnvkit/cnvkit.py --sorted_bam bam_file --ref GRCh38 --python3_path /usr/bin/python3_dir --cngain 5 --cnsize_min 50000 --run_AA`
I have ruled out some common factors that may introduce errors such as PCR duplicate. Although no cause has been found for the time being, but still thank you for your reply, I will continue to think about this issue.
Best.
